name: Trivy

on:
  push:
    branches:
      - main
      - unstable
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # “At 00:00 on Sunday.”
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml

      - name: Upload Results to GitHub Security
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Generate Summary Report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
          format: "table"
          skip-setup-trivy: true
